import React,{useEffect,useState} from 'react';
import { useNavigate,useParams } from 'react-router-dom';
import Layout from '../components/Layout.jsx';
import api from '../services/api.js';
const initial={name:'',sku:'',description:'',quantity:0,costPrice:'',sellingPrice:'',lowStockThreshold:''};
export default function ProductForm(){
 const {id}=useParams(); const edit=Boolean(id); const [form,setForm]=useState(initial); const [error,setError]=useState(''); const nav=useNavigate();
 useEffect(()=>{if(edit) api.get(`/products/${id}`).then(r=>{const p=r.data;setForm({name:p.name,sku:p.sku,description:p.description||'',quantity:p.quantity,costPrice:p.cost_price??'',sellingPrice:p.selling_price??'',lowStockThreshold:p.low_stock_threshold??''})})},[id]);
 const submit=async(e)=>{e.preventDefault();setError('');try{edit?await api.put(`/products/${id}`,form):await api.post('/products',form);nav('/products')}catch(err){setError(err.response?.data?.message||'Save failed')}};
 return <Layout><h1 className="text-3xl font-bold">{edit?'Edit Product':'Add Product'}</h1><form onSubmit={submit} className="card mt-6 grid gap-4 md:grid-cols-2">{error&&<div className="md:col-span-2 rounded bg-red-100 p-3 text-red-700">{error}</div>}<label>Name<input className="input mt-1" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>SKU<input className="input mt-1" required value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})}/></label><label className="md:col-span-2">Description<textarea className="input mt-1" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Quantity<input className="input mt-1" type="number" min="0" required value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></label><label>Cost Price<input className="input mt-1" type="number" step="0.01" min="0" value={form.costPrice} onChange={e=>setForm({...form,costPrice:e.target.value})}/></label><label>Selling Price<input className="input mt-1" type="number" step="0.01" min="0" value={form.sellingPrice} onChange={e=>setForm({...form,sellingPrice:e.target.value})}/></label><label>Low Stock Threshold<input className="input mt-1" type="number" min="0" placeholder="Leave empty to use default" value={form.lowStockThreshold} onChange={e=>setForm({...form,lowStockThreshold:e.target.value})}/></label><div className="md:col-span-2 flex gap-3"><button className="btn">Save Product</button><button type="button" className="btn-secondary" onClick={()=>nav('/products')}>Cancel</button></div></form></Layout>
}
